Add Collection,Stream, LinkedList,ArrayList. Updated funções e método…
paulorievrs/java4noobs pull request #18
Opened 2021-04-18 18:35 UTC by midhatdrops

2021-04-18 23:44 UTC, FerroEduardo requested changes
Gostei muito do conteúdo, só precisa fazer algumas alterações

2021-04-18 23:44 UTC, FerroEduardo commented on 3 - Básico/12-Funcoes-Metodos.md
> +    System.out.printlnnovaStringSemEspaco;
Ficou faltando os parênteses da função

2021-04-18 23:44 UTC, FerroEduardo commented on 4 - Intermediário/07-LinkedList-vs-ArrayList.md
> +O segundo motivo é que Arrays puros só trabalham com tipos primitivos, o que limita bastante quando falamos de POO, nesse modo, as Lists colaboram muito ao permitir que usemos Objetos como valores de
Em Java, também é possível criar arrays de objetos. Segue um exemplo: [https://replit.com/@FerroEduardo/ObjectArray](https://replit.com/@FerroEduardo/ObjectArray)

2021-04-18 23:44 UTC, FerroEduardo commented on 4 - Intermediário/07-LinkedList-vs-ArrayList.md
> +No caso de LinkedList, o algoritmo usado utiliza o conceito de HashTable e Tabela de Dispersão, os quais não serão abordados nesse tópico porém são o que garantem que LinkedList tenham uma performanc
Tem um typo no final

2021-04-19 00:05 UTC, midhatdrops commented
Corrigido!

2021-04-19 00:14 UTC, FerroEduardo requested changes

2021-04-19 00:14 UTC, FerroEduardo commented on 3 - Básico/12-Funcoes-Metodos.md
> +    System.out.println(novaStringSemEspaco;
Faltou outro parêntese.

2021-04-19 00:14 UTC, FerroEduardo commented on 4 - Intermediário/07-LinkedList-vs-ArrayList.md
> +No caso de LinkedList, o algoritmo usado utiliza o conceito de HashTable e Tabela de Dispersão, os quais não serão abordados nesse tópico porém são o que garantem que LinkedList tenham uma performanc
Quando eu disse typo era de erro de grafia, acho que me expressei errado. O erro é `posiçaõ`.

2021-04-19 00:27 UTC, midhatdrops commented on 4 - Intermediário/07-LinkedList-vs-ArrayList.md
> +No caso de LinkedList, o algoritmo usado utiliza o conceito de HashTable e Tabela de Dispersão, os quais não serão abordados nesse tópico porém são o que garantem que LinkedList tenham uma performanc
Corrigido ambos, mal de tentar corrigir os erro de digitação pelo cel rs .

2021-04-19 00:41 UTC, FerroEduardo approved these changes

2021-04-22 22:24 UTC, merged