Listas imutaveis
paulorievrs/java4noobs pull request #20
Opened 2021-10-31 17:38 UTC by pgjbz

Adição sobre listas imutaveis, considero isto uma informação importante, até mesmo para evitar erros com o Arrays.asList e List.of, como já cometi no inicio de minha carreira como dev Java

2021-10-31 19:25 UTC, FerroEduardo requested changes
Conteúdo muito bacana! Só precisa fazer algumas alterações como:
- Corrigir alguns erros como:
    - Imutavel -> Imutável
    - Mutavel -> mutável
    - java -> Java
    - snipet -> snippet (não entendi mt a proposta desse comentário no código)
    - instancia -> instância
    - método defaul -> método default
    - adiocionamos -> adicionamos
- Alterar o tab para 4 espaços em vez do '\t'
    - O espaçamento fica muito grande aqui no GitHub
- (opcional) Quebrar os comentários em mais linhas, acredito que fica melhor para ler
- (opcional) Acho que os `import` não são muito necessários
- Adicionar o link para o arquivo no README.md da pasta raiz
- Remover/comentar link de próximo conteúdo
- Alterar o link do arquivo anterior (07-LinkedList-vs-ArrayList.md) para apontar para o seu (08-Listas-imutaveis.md)

Uma coisa que reparei é que os parágrafos não possuem pausas (ponto final). Seria bom dar uma refatorada nesses textos.  
Mas em relação à proposta do conteúdo, gostei bastante. Costumava usar alguns desses métodos sem saber como realmente funcionavam.

2021-10-31 20:19 UTC, pgjbz commented
Ajustes realizados, obrigado pelas correções

2021-11-01 13:36 UTC, pgjbz commented on README.md
> +8. 🔠 [Listas Imutáveis](/4%20-%20Intermedi%C3%A1rio/08-Listas-imutaveis.md)
adição do tópico no README.md

2021-11-01 13:36 UTC, pgjbz commented on 4 - Intermediário/07-LinkedList-vs-ArrayList.md
> +[Próximo](./08-Listas-imutaveis.md) - Listas imutaveis
Adição do próximo no tópico anterior

2021-11-02 15:58 UTC, pgjbz commented on 4 - Intermediário/08-Listas-imutaveis.md
> +É possivel criar uma lista imutável utilizando os métodos da ```Collections.unmodifiableList(lista)```, porém é meio verboso este tipo de método, precisamos da instância da lista e depois passa-la co
Adição da documentação da interface List, List.of e Arrays.asList

2021-11-02 19:03 UTC, FerroEduardo approved these changes
Obrigado pela contribuição!

2021-11-02 19:03 UTC, merged