Sets
paulorievrs/java4noobs pull request #21
Opened 2021-11-12 00:06 UTC by pgjbz

Dando sequencia na explicação das coleções do Java, agora venho com o Set e a explicação de 3 implementações diferentes da interface

2021-11-12 01:34 UTC, FerroEduardo requested changes
Conteúdo muito bacana, só preciso de pequenas correções.
- Observei que os links da documentação são de versões diferentes. Para deixar padronizado, peço que deixe todos eles na versão 11 do JDK.

2021-11-12 01:34 UTC, FerroEduardo commented on 4 - Intermediário/09-Sets.md
> +O modo de trabalho com o TreeSet é praticamente o mesmo dos já mostrados aqui, com a grande diferença desta implementação utilizar o método [compareTo](https://www.w3schools.com/java/ref_string_compa
Seria bacana explicar que o TreeSet utiliza os métodos(compare/compareTo) em vez de hash por debaixo dos panos ao realizar as operações(add,remove,contains), imagino que fique mais claro para o leitor.
- Trocar o link do `compareTo` para `https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Comparable.html`.

2021-11-12 01:34 UTC, FerroEduardo commented on 4 - Intermediário/09-Sets.md
> +A instanciação do HashSet é simples, basicamente temos o padrão `Set\<Tipo> nome = new HashSet<>();` com isso já temos a instancia para trabalharmos.
Corrigir o `Set\<Tipo>`

2021-11-12 01:34 UTC, FerroEduardo commented on 4 - Intermediário/09-Sets.md
> +         Set<Integer> intSet = new HashSet<>();
Corrigir indentação

2021-11-12 01:43 UTC, FerroEduardo commented
Talvez algo que nós podemos fazer futuramente é organizar os links de documentações e padronizar para a versão LTS mais recente. Creio que isso ajude a evitar falhas ao comentar sobre métodos.  
Digo isso, pois existem métodos comentados nesse PR que não estão presentes no JDK 8, como o `Set.of()`. Não verifiquei se isso ocorreu no PR anterior, mas é algo que pode ser evitado.

Não veja essa mensagem como uma crítica, é mais um comentário sobre o futuro do repositório. Acho até que poderia ser uma issue válida.

2021-11-12 11:16 UTC, pgjbz commented
> Talvez algo que nós podemos fazer futuramente é organizar os links de documentações e padronizar para a versão LTS mais recente. Creio que isso ajude a evitar falhas ao comentar sobre métodos. Digo isso, pois existem métodos comentados nesse PR que não estão presentes no JDK 8, como o `Set.of()`. Não verifiquei se isso ocorreu no PR anterior, mas é algo que pode ser evitado.
> 
> Não veja essa mensagem como uma crítica, é mais um comentário sobre o futuro do repositório. Acho até que poderia ser uma issue válida.

Concordo em padronizar para a ultima versão LTS, porém temos que tomar cuidado, pois a 8, 11 e 17 são LTS e muitas vezes o Java 8 ainda é usado na maior parte dos projetos, o que eu fiz agora foi especificar que o `Set.of` só existe em versões acima do Java 8, creio q inicialmente vou tomar mais este cuidado nas proximas colaborações em relação a isso.

2021-11-13 20:58 UTC, FerroEduardo approved these changes

2021-11-13 20:59 UTC, merged