(feat): Added Interface and fixed other links
paulorievrs/java4noobs pull request #32
Opened 2022-07-20 01:58 UTC by midhatdrops

Adicionado arquivo sobre interfaces, mudei as referências dos outros arquivos para deixar o Readme de Interfaces mais perto dos outros de POO visando dar mais facilidade ao leitor ao avançar pelos conceitos de POO, foi abordado polimorfismo e algumas implementações de interface.

2022-08-05 20:29 UTC, FerroEduardo requested changes

2022-08-05 20:29 UTC, FerroEduardo commented on 4 - Intermediário/06-Interfaces.md
> +> Entretanto, a partir do Java 9 podemos usar também métodos privados, padrão e estáticos dentro do nosso código, permitindo que coloquemos alguns métodos padrões já inseridos na execução de algum ou
Java 8 já tinha métodos `default` e `static`
[9.4.3. Interface Method Body](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.4)

2022-08-05 20:29 UTC, FerroEduardo commented on 4 - Intermediário/06-Interfaces.md
> +![CorrentistaSupreme](../img/interfaces-explo1.png)
Trocar todas as imagens por texto para melhorar a visualização mobile
```java
class Program {
    public static void main(String[] args) {
        ...
    }
}
```

2022-08-05 20:29 UTC, FerroEduardo commented on 4 - Intermediário/06-Interfaces.md
> +Vale ressaltar que também há implementações possíveis para o uso de _static_ e _abstract_ nas interfaces a partir do Java 9.
Quanto ao `abstract`, todos os métodos de uma interface são implicitamente abstratos, com exceção quando outros modificadores são utilizados

2022-08-07 22:31 UTC, midhatdrops commented on 4 - Intermediário/06-Interfaces.md
> +> Entretanto, a partir do Java 9 podemos usar também métodos privados, padrão e estáticos dentro do nosso código, permitindo que coloquemos alguns métodos padrões já inseridos na execução de algum ou
Corrigido no commit último commit

2022-08-07 22:31 UTC, midhatdrops commented on 4 - Intermediário/06-Interfaces.md
> +![CorrentistaSupreme](../img/interfaces-explo1.png)
Corrigido no commit último commit

2022-08-07 22:32 UTC, midhatdrops commented on 4 - Intermediário/06-Interfaces.md
> +Vale ressaltar que também há implementações possíveis para o uso de _static_ e _abstract_ nas interfaces a partir do Java 9.
Corrigido no commit último commit

2022-08-13 01:42 UTC, FerroEduardo approved these changes

2022-08-13 01:43 UTC, merged