Melhoria a categoria sobre exceptions
paulorievrs/java4noobs pull request #37
Opened 2023-06-09 00:40 UTC by GustavoMMartins

Estava dando uma olhada no repositório, e decidi fazer uma contribuição sobre exceptions, que eu considero um assunto importante dentro do Java e considerando que já tive entrevistas de emprego que caíram sobre a parte teórica de exceções, fiz uma atualização falando sobre os tipos de exceções e como criar a sua própria para utilização dentro do seu código.

2023-06-13 22:17 UTC, FerroEduardo requested changes

2023-06-13 22:17 UTC, FerroEduardo commented on 3 - Básico/17-Excecoes.md
> +> OutOfMemoryError -> Esse erro se dá quando a JVM não consegue mais alocar nada na memória.
```suggestion
> OutOfMemoryError -> Esse erro se dá quando a JVM não consegue alocar mais memória.
```

2023-06-13 22:17 UTC, FerroEduardo commented on 3 - Básico/17-Excecoes.md
> +> StackOverflowError ->  Acontece quando a quantidade de memória da pilha é ultrapassada.
```suggestion
> StackOverflowError -> Acontece quando a quantidade de memória da pilha é ultrapassada.
```

2023-06-13 22:17 UTC, FerroEduardo commented on 3 - Básico/17-Excecoes.md
> +> NoClassDefFoundError -> Diz que a JVM tentou buscar internamente a pela sua classe e não a encontrou.
```suggestion
> NoClassDefFoundError -> Ocorre quando a JVM não consegue encontrar a sua classe.
```

2023-06-13 22:17 UTC, FerroEduardo commented on 3 - Básico/17-Excecoes.md
> +As exceções são problemas que podem ocorrer durante a execução de um programa Java, mas não causam um colapso total do programa, e podem ser previstas e tratadas através dos blocos de exceção. As exc
```suggestion
As exceções são problemas que podem ocorrer durante a execução de um programa Java, mas não causam um colapso total do programa, e podem ser previstas e tratadas através dos blocos de exceção. As exceções são divididas em duas categorias: exceções verificadas (checked exceptions) e exceções não verificadas (unchecked exceptions). As exceções verificadas são aquelas que exigem tratamento explícito, ou seja, necessitam da utilização dos blocos de exceções, enquanto as exceções não verificadas não requerem tratamento explícito ou a utilização dos blocos de exceções, mas é considerado boa pratica a utilização, pois caso não tenha o bloco Try-Catch, o seu programa se encerrará com a exception.
```

2023-06-13 22:17 UTC, FerroEduardo commented on 3 - Básico/17-Excecoes.md
> +Você também pode criar suas exceções no Java para algum determinado fluxo ou alguma regra de negócio que você tenha em seu código, assim facilitando a localização e descobrindo o que pode ter acontec
```suggestion
Você também pode criar suas exceções no Java para algum determinado fluxo ou alguma regra de negócio que possa disparar algum erro, assim facilitando a localização e descobrindo o que pode ter acontecido pelo caminho. Para isso, basta criar uma classe que herde alguma classe de erro, como `RuntimeException` ou `Exception`.
```

2023-06-13 23:12 UTC, gustavommartins commented on img/arvore_exceptions.jpeg
Como não consegui encontrar/lembrar de onde eu tirei a imagem para evitar problemas criei uma no paint.

2023-06-13 23:30 UTC, gustavommartins commented on 3 - Básico/17-Excecoes.md
> +Geralmente ao construir um programa somos deparados com alguns erros no fluxo das nossas aplicações, mas não se preocupe com esse tópico você irá aprender um pouco mais sobre elas, e com isso chegamo
Texto reformulado, tentei transformar em um texto mais introdutório ao módulo.

2023-06-13 23:44 UTC, gustavommartins commented on 3 - Básico/17-Excecoes.md
> +As exceções são problemas que podem ocorrer durante a execução de um programa Java, mas não causam um colapso total do programa, e podem ser previstas e tratadas através dos blocos de exceção. As exc
Sugestões aceitas e adicionei que as exceções não verificadas são as RuntimeException.

2023-06-15 23:05 UTC, FerroEduardo commented on img/arvore_exceptions.jpeg
Para criação de diagramas, recomendo o [draw.io](https://draw.io/)

2023-06-15 23:06 UTC, FerroEduardo approved these changes

2023-06-15 23:07 UTC, merged