Adição de conteúdo
paulorievrs/java4noobs pull request #39
Opened 2023-08-27 20:40 UTC by viniciusenari

Fiz as seguintes alterações:
- Mudei a seção sobre "Declarações de variáveis" para "Variáveis". A explicação anterior tratava a inicialização de uma variável como uma declaração e não explicava a diferença entre declarar, atribuir e inicializar uma variável.
- Adicionei exemplos na seção de operadores lógicos.
- Adicionei Switch Expressions na seção de estruturas condicionais.
- Adicionei uma explicação sobre métodos sobrecarregados na seção sobre métodos.
- Adicionei uma explicação mais detalhada sobre static vs non-static e exemplos.
- Adicionei novas seções para Herança, Modificadores de acesso e Polimorfismo.

2023-08-28 01:54 UTC, midhatdrops requested changes
Achei bem daora e didática a forma explicada, abordo uns conceitos bem chatinhos de aprender a primeira vez em Java. Só alteraria um ponto ou outro que deixei elencado junto de algumas sugestões de melhoria.

2023-08-28 01:54 UTC, midhatdrops commented on 3 - Básico/08-EstruturasCondicionais.md
> +A versão 12 do Java adicionou uma funcionalidade chamada de Switch Expression que permite que o switch case seja utilizado de uma maneira mais concisa e simples. Nem todas as empresas utilizam essa v
A função de retorno direto no switch case na switch expression  na verdade foi inserida no java 13 (aka Case L). Acho legal alterar o texto para "A partir da versão 12 do Java". Também vale adicionar um exemplo de um switch case sem usar a expression

2023-08-28 01:54 UTC, midhatdrops commented on 4 - Intermediário/08-Polimorfismo.md
> +Polimorfismo dinâmico ocorre quando um método é sobrescrito por uma subclasse após a compilação, ou seja enquanto o código está sendo executado. Vamos pegar pro exemplo mais uma vez as classes `Anima
Acho que aqui vale a pena comentar ou referenciar a seção de variáveis, pois no fim você usa esse conceito de "inicialização tardia" de uma variável, mas ficou bem didático da forma que você colocou. Só sugestão mesmo.

2023-08-28 01:54 UTC, midhatdrops commented on 4 - Intermediário/09-ModificadoresDeAcesso.md
> +- `default` ou `padrão`: A classe, método ou atributo só pode ser acessado por classes do mesmo pacote. Para utilizar esse modificador, basta não escrever nada.
Aqui só retirar o "padrão", pois pela forma que está parece que é uma opção de modificador de acesso. Acho que pode colocar no texto seguinte que é a forma de acesso padrão do Java.

2023-08-29 00:31 UTC, viniciusenari commented on 3 - Básico/08-EstruturasCondicionais.md
> +A versão 12 do Java adicionou uma funcionalidade chamada de Switch Expression que permite que o switch case seja utilizado de uma maneira mais concisa e simples. Nem todas as empresas utilizam essa v
Corrigi o número da versão. Não adicionei um exemplo de switch case sem expression pois ja [existia no repositório.](https://github.com/paulorievrs/java4noobs/blob/master/3%20-%20B%C3%A1sico/08-EstruturasCondicionais.md#switch-case)

2023-08-29 00:32 UTC, viniciusenari commented on 4 - Intermediário/08-Polimorfismo.md
> +Polimorfismo dinâmico ocorre quando um método é sobrescrito por uma subclasse após a compilação, ou seja enquanto o código está sendo executado. Vamos pegar pro exemplo mais uma vez as classes `Anima
Bom ponto, adicionei uma menção à seção de variáveis.

2023-08-29 00:33 UTC, viniciusenari commented on 4 - Intermediário/09-ModificadoresDeAcesso.md
> +- `default` ou `padrão`: A classe, método ou atributo só pode ser acessado por classes do mesmo pacote. Para utilizar esse modificador, basta não escrever nada.
Realmente dava para confundir da maneira que estava. Alterei para não listar o padrão como um modificador e adicionei um texto explicando o comportamento padrão caso nenhum modificador seja utilizado.

2023-08-29 19:33 UTC, FerroEduardo commented on 3 - Básico/08-EstruturasCondicionais.md
> +A versão 12 do Java adicionou uma funcionalidade chamada de Switch Expression que permite que o switch case seja utilizado de uma maneira mais concisa e simples. Nem todas as empresas utilizam essa v
Pelo que vi, a `Switch Expression` foi lançada no JDK 14 e estava como preview nos JDKs 12 e 13

2023-08-29 19:53 UTC, FerroEduardo requested changes
Gostei muito e ficou bem didático. Só preciso que corrija todos os links que apontavam para o próximo conteúdo, ex:  
Atualmente:
- `05-Utilizando-Classe.md` -> `07-Collections-e-Stream.md`

Correto:
- `05-Utilizando-Classe.md` -> `06-Heranca.md`

2023-08-29 23:28 UTC, viniciusenari commented
Esclareci sobre a versão em que foi adicionado switch expressions e arrumei os links para as próximas páginas.

2023-08-29 23:33 UTC, midhatdrops commented
Acho que está tudo ok agora. Obrigado pela contribuição @viniciusenari  !

2023-08-29 23:34 UTC, merged