Feature/feature andreza
paulorievrs/java4noobs pull request #41
Opened 2024-05-31 04:24 UTC by andreza-vilar

adicionando informações novas sobre editores de texto

2024-06-01 13:59 UTC, FerroEduardo requested changes

2024-06-01 13:59 UTC, FerroEduardo commented on README.md
> +9. Abra um Pull Request
Acho que não é necessário detalhar o fork nesse nível. Além do primeiro item já deixar esses passos implícitos, esse texto segue um padrão que outros repositórios também seguem

2024-06-01 13:59 UTC, FerroEduardo commented on 2 - Ambiente/2.2-Editor-de-Texto.md
> +Disponível em duas edições: Community Edition (gratuita e de código aberto) e Ultimate Edition (paga, com recursos adicionais). A Community Edition é ideal para iniciantes. A versão Ultimate pode ser
Além do e-mail institucional, acho que vale a pena comentar sobre o [GitHub Student Developer Pack](https://education.github.com/pack)

2024-06-07 03:04 UTC, andreza-vilar commented on README.md
> +9. Abra um Pull Request
perfeito, vou alterar

2024-06-09 23:05 UTC, FerroEduardo approved these changes

2024-06-09 23:06 UTC, FerroEduardo commented
Obrigado pela contribuição :)

2024-06-09 23:06 UTC, merged